#!/bin/bash
#auther = song

JAVA_HOME=/usr/java/jdk1.7.0_55
TOMCAT_HOME=/usr/local/tomcat7
start_tomcat=$TOMCAT_HOME/bin/startup.sh
stop_tomcat=$TOMCAT_HOME/bin/shutdown.sh

start() {
    echo -n "start tomcat"
    ${start_tomcat}
    echo "tomcat start OK"
}

stop() {
    echo -n "shutdown tomcat"
    ${stop_tomcat}
    echo "tomcat stop OK"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 5
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
esac
exit 0


